{
"targets": [
    {
      "target_name": "<(module_name)",
      "sources": [
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_A2NLSF.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_ana_filt_bank_1.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_apply_sine_window.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_array_maxabs.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_autocorr.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_biquad.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_biquad_alt.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_burg_modified.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_bwexpander.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_bwexpander_32.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_CNG.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_code_signs.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_control_audio_bandwidth.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_control_codec_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_corrMatrix_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_create_init_destroy.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_dec_API.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_decode_core.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_decode_frame.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_decode_parameters.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_decode_pitch.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_decode_pulses.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_decoder_set_fs.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_detect_SWB_input.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_div_oabi.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_enc_API.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_encode_frame_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_encode_parameters.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_encode_pulses.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_find_LPC_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_find_LTP_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_find_pitch_lags_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_find_pred_coefs_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_gain_quant.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_HP_variable_cutoff_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_init_encoder_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_inner_prod_aligned.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_interpolate.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_k2a.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_k2a_Q16.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LBRR_reset.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_lin2log.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_log2lin.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LP_variable_cutoff.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LPC_inv_pred_gain.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LPC_synthesis_filter.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LPC_synthesis_order16.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LSF_cos_table.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LTP_analysis_filter_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_LTP_scale_ctrl_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_MA.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF2A.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF2A_stable.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF_MSVQ_decode.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF_MSVQ_encode_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF_stabilize.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF_VQ_rate_distortion_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF_VQ_sum_error_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NLSF_VQ_weights_laroia.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_noise_shape_analysis_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NSQ.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_NSQ_del_dec.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_pitch_analysis_core.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_pitch_est_tables.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_PLC.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_prefilter_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_process_gains_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_process_NLSFs_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_quant_LTP_gains_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_range_coder.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_regularize_correlations_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_down2.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_down2_3.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_down3.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_AR2.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_ARMA4.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_copy.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_down4.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_down_FIR.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_IIR_FIR.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_up2_HQ.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_private_up4.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_rom.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_resampler_up2.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_residual_energy16_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_residual_energy_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_scale_copy_vector16.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_scale_vector.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_schur.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_schur64.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_shell_coder.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_sigm_Q15.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_solve_LS_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_sort.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_sum_sqr_shift.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_gain.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_LTP.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_NLSF_CB0_10.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_NLSF_CB0_16.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_NLSF_CB1_10.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_NLSF_CB1_16.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_other.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_pitch_lag.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_pulses_per_block.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_sign.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_tables_type_offset.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_VAD.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_VQ_nearest_neighbor_FIX.c",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/SKP_Silk_warped_autocorrelation_FIX.c",
        "libSilkCodec/src/decoder.c",
        "libSilkCodec/src/encoder.c",
        "src/codec.c"
      ],
      "cflags": [ "-Wno-unused-variable", "-Wno-unused-but-set-variable" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "libSilkCodec/src/include/",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/interface/",
        "libSilkCodec/silk/src/SILK_SDK_SRC_ARM_v1.0.9/src/",
      ],
      "conditions:": [
        ["OS=='win'", {"libraries": ["-lnode-silk.lib"] }],
        ["OS=='linux'", {"libraries": ["-lnode-silk.lib"] }]
      ]
    },
    {
      "target_name": "action_after_build",
      "type": "none",
      "dependencies": [ "<(module_name)" ],
      "copies": [
          {
            "files": [ "<(PRODUCT_DIR)/<(module_name).node" ],
            "destination": "<(module_path)"
          }
      ]
    }
  ]
}